sgdevcamp2025/smiletogether

frontend/package.json, frontend/pnpm-lock.yaml, frontend/public/mockServiceWorker.js, frontend/src/apis/workspace/worksapce.ts, frontend/src/components/ui/button.tsx, frontend/src/components/ui/card.tsx, frontend/src/hooks/WorkSpace/useWorkSpaceQuery.tsx, frontend/src/lib/https.ts, frontend/src/lib/utils.ts, frontend/src/main.tsx, frontend/src/mocks/browser.ts, frontend/src/mocks/dummy.json, frontend/src/mocks/handlers.ts, frontend/src/pages/workspace/WorkspaceListPage.tsx, frontend/src/routers/index.tsx, frontend/tsconfig.app.json, frontend/vite.config.ts
> #1 
> 워크스페이스 리스트 페이지 추가 및 Mock Service Worker 설정
=>  [FE] Feat : 워크스페이스 리스트 페이지 추가 및 Mock Service Worker 설정

backend/chat-server/gradlew, backend/chat-server/gradlew.bat, backend/chat-server/src/main/java/com/smiletogether/chatserver/config/ChatConfig.java, backend/chat-server/src/main/java/com/smiletogether/chatserver/controller/interceptor/FilterChannelInterceptor.java, config/docker-compose-chat-server.yml
closed#56 
- 혹시 몰라서 스톰프 연결 관련 인터셉터 구현해놨습니다.
- 해결안되시면, 서버의 로그도 같이 보야주세요.
=> [BE] fix: 테스트 연동 안되는 문제 

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/apis/channel/dto.ts, frontend/src/apis/channel/index.ts, frontend/src/apis/workspace/dto.ts, frontend/src/apis/workspace/index.ts, frontend/src/components/frame/workspace/SidebarContainer.tsx, frontend/src/components/frame/workspace/WorkspaceContentSidebar/WorkspaceChannelSidebar.tsx, frontend/src/components/frame/workspace/WorkspaceSidebar.tsx, frontend/src/components/ui/accordion.tsx, frontend/src/components/workspace/WorkspaceDashboard/index.tsx, frontend/src/components/workspace/WorkspaceSideBar/WorkspaceSidebarSection.tsx, frontend/src/hooks/WorkSpace/useUserWorkspaceQuery.tsx, frontend/src/hooks/WorkSpace/useUserWorkspacesQuery.tsx, frontend/src/hooks/channel/useWorkspaceChannelListQuery.tsx, frontend/src/mocks/dummy.json, frontend/src/mocks/handlers.ts, frontend/src/pages/workspace/WorkspaceListPage.tsx, frontend/tailwind.config.js
=> [FE] feat: WorkspaceChannelSidebar 를 구현한다

backend/space-server/prisma/migrations/20250212144211_change_workspace_id_to_uuid/migration.sql, backend/space-server/prisma/schema.prisma, backend/space-server/src/app.controller.ts, backend/space-server/src/decorators/user-id.decorator.ts, backend/space-server/src/guards/auth.guard.ts, backend/space-server/src/workspace/dto/create-workspace.dto.ts, backend/space-server/src/workspace/dto/search-workspace.dto.ts, backend/space-server/src/workspace/dto/workspace-detail.dto.ts, backend/space-server/src/workspace/dto/workspcae-response.dto.ts, backend/space-server/src/workspace/workspace.controller.ts, backend/space-server/src/workspace/workspace.service.ts
> - closed #51
> PK 타입을 변경했습니다 
=> [BE] feat: PK type 변경

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/common/Message.tsx, frontend/src/components/common/MessageBox.tsx, frontend/src/components/common/UserHoverCard.tsx, frontend/src/hooks/channel/useGetChaneel.tsx, frontend/src/hooks/channel/useGetMessage.ts, frontend/src/hooks/channel/useSendMessage.ts, frontend/src/hooks/channel/useWebSocket.ts, frontend/src/pages/channel/ChannelPage.tsx, frontend/src/routers/index.tsx, frontend/src/types/chat.ts, frontend/src/types/user.ts, frontend/tailwind.config.js
#55 
1. 웹 소켓 관련 훅 부분들을 나름 분리하기는 했는데 이 부분 관련해서 많은 피드백해주시면 좋을 것 같습니다!
=> [FE] feat: 채널의 채팅 페이지 웹 소켓 및 UI 구현

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/channel/ChannleDelete.tsx, frontend/src/components/channel/infoModal/ChannleInfoModal.tsx, frontend/src/components/channel/infoModal/Info.tsx, frontend/src/components/channel/infoModal/Members.tsx, frontend/src/components/channel/infoModal/index.ts, frontend/src/components/common/ChatHeader.tsx, frontend/src/components/frame/workspace/MainNavigationSidebar.tsx, frontend/src/components/frame/workspace/WorkspaceSidebar.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/components/ui/input.tsx, frontend/src/components/ui/resizable.tsx, frontend/src/components/ui/switch.tsx, frontend/src/components/ui/textarea.tsx, frontend/src/components/workspace/Modal/WorkspaceUserInviteModal.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/index.tsx, frontend/src/hooks/channel/useWebSocket.ts, frontend/src/mocks/dummy.json, frontend/src/pages/channel/ChannelPage.tsx, frontend/src/routers/index.tsx
#74 
1. ChatHeader 컴포넌트가 정말 많이많이 긴데.. 이 부분은 기능을 전체적으로 구현한 다음에 분리하는게 편할 것 같아서 일단 내비뒀습니다.. ㅜㅜ
=> [FE] feat: 채널 채팅 페이지 상세 Ui 구현

frontend/src/components/channel/ChannelMenu.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/index.tsx, frontend/src/components/workspace/WorkspaceMenu.tsx
- #84 
- 워크스페이스 나가기 vs 삭제 - 조건부 UI 처리 로직 추가
- role 확인 로직 추가하기
- UI 반영
=> [FE] feat: 워크스페이스 나가기 vs 삭제 - 조건부 UI 처리 로직 추가

.github/workflows/node.js.yml
=> [FE] deploy : 배포 문서를 수정한다

frontend/src/pages/login/LoginPage.tsx
=> [FE] test : test를 위한 커밋

backend/chat-server/docker-compose.yml, backend/history-server/docker-compose.yml
=> [BE] conflict 해결을 위한 pr

backend/history-server/src/main/java/com/smiletogether/historyserver/service/ChannelMessageService.java
=> [BE] fix: 정렬 오름차순으로 수정

backend/space-server/src/channel/channel.controller.ts, backend/space-server/src/channel/channel.service.ts, backend/space-server/src/common/PrismaExceptionFilter.ts, backend/space-server/src/main.ts
> - #120 
원래 DB에서 데이터 검색하거나 다루다가 문제생기면 모두 500에러로 리턴했는데 데이터 형식이 다르거나 데이터가 없는 경우, 필드 누락된 경우 등은 안내 메세지가 따로 나오면 연동하기 더 편할 것 같아서 채널 유저 검색 api 만들고 에러 처리도 간단하게만 했습니다
=> [BE] feat: 채널에서 유저 검색 및 공통 에러 처리

backend/history-server/src/main/java/com/smiletogether/historyserver/config/WebConfig.java, backend/history-server/src/main/java/com/smiletogether/historyserver/service/ChannelMessageService.java, backend/history-server/src/main/resources/dummy_messages.json
=> [BE] fix: 채팅 리스트 정렬 수정

frontend/src/apis/user/index.ts, frontend/src/apis/workspace/dto.ts, frontend/src/apis/workspace/index.ts, frontend/src/components/modals/workspace/WorkspaceUserInviteModal.tsx, frontend/src/hooks/workspace/useWorkspaceInviteLinkUrlMutation.ts, frontend/src/lib/https.ts, frontend/src/lib/utils.ts, frontend/src/mocks/handlers.ts, frontend/src/pages/login/ConfirmEmailPage.tsx, frontend/src/pages/workspace/WorkspaceJoinPage.tsx, frontend/src/routers/index.tsx, package.json, pnpm-lock.yaml
=> [FE] feat : 프론트 동기화를 위한 pr입니다

frontend/src/apis/workspace/index.ts, frontend/src/components/frame/workspace/MainNavigationSidebar.tsx, frontend/src/components/frame/workspace/WorkspaceHeader.tsx, frontend/src/components/frame/workspace/WorkspaceSidebar.tsx, frontend/src/components/modals/workspace/WorkspaceUserInviteModal.tsx, frontend/src/components/ui/button.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/WorkspaceChannelListItem.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/WorkspaceDMs.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/index.tsx, frontend/src/components/workspace/WorkspaceCreationProcess/index.tsx, frontend/src/hooks/workspace/useGetIsMemberOfWorkspaceByInviteLinkQuery.ts, frontend/src/lib/https.ts, frontend/src/pages/workspace/WorkspaceListPage.tsx
- #147 
- 가독성을 고려한 워크스페이스 style 수정
- 워크스페이스 사이드바 색상
- 워크스페이스 판낼 텍스트 크기
- 유저 초대 api 명세 변경사항 적용
- 워크스페이스 생성 도중 나가기 기능 추가
- 유저 초대에서 사용되는 프론트 도메인 변수 환경변수로 추출
- etc
- env 수정하였습니다.
```
VITE_BASE_SERVER_API_URL = http://localhost:8090
VITE_BASE_CLIENT_API_URL = http://localhost:5173
```
=> [FE] refactor: api 명세 변경 적용 및 style 리팩토링 

frontend/src/apis/channel/index.ts, frontend/src/apis/user/index.ts, frontend/src/apis/workspace/dto.ts, frontend/src/apis/workspace/index.ts, frontend/src/components/common/ChannelTagInput.tsx, frontend/src/components/common/Message.tsx, frontend/src/components/frame/workspace/WorkspaceFrame.tsx, frontend/src/components/frame/workspace/WorkspaceSidebar.tsx, frontend/src/components/modals/workspace/WorkspaceUserInviteModal.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/WorkspaceChannelListItem.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/index.tsx, frontend/src/components/workspace/WorkspaceCreationProcess/StepSetInviteUsers.tsx, frontend/src/hooks/channel/useDeleteMessage.ts, frontend/src/hooks/channel/useEditMessage.ts, frontend/src/hooks/channel/useSendMessage.ts, frontend/src/lib/https.ts, frontend/src/mocks/handlers.ts, frontend/src/pages/channel/ChannelPage.tsx, frontend/src/pages/login/ConfirmEmailPage.tsx, frontend/src/pages/login/LoginPage.tsx, frontend/src/pages/workspace/WorkspaceListPage.tsx, frontend/src/stores/userOriginStore.ts, frontend/src/types/user.ts
=> [FE] feat : 기능들을 연결한다

frontend/src/apis/channel/dto.ts, frontend/src/components/frame/workspace/WorkspaceFrame.tsx, frontend/src/components/workspace/WorkspaceCreationProcess/StepSetInviteUsers.tsx, frontend/src/lib/utils.ts, frontend/src/pages/channel/ChannelPage.tsx
> - #178 
api 명세 바꾼게 적용이 안되어서 undefined 뜨는거 고쳤습니다
그리고 userOriginStore에서 userId를 호출하던데 이렇게 userOriginStore에서 호출하면 이미 로그인이 되어있을 경우(어제 로그인했다가 브라우저 끄고 오늘 다시 켰는데 토큰이 남아있을 경우는 로그인 되어있다고 판단됨)는 데이터가 사라져서 오류가 나서 userId는 토큰에서 해독하는걸로 바꿨습니다
=> [FE] refactor: channelName 수정, 유저정보 호출 오류 수정

frontend/src/components/frame/workspace/WorkspaceFrame.tsx, frontend/src/pages/channel/ChannelPage.tsx, frontend/src/stores/userStore.ts
> - #188
useUserStore에 유저정보 저장했습니다
=> [FE] fix : 유저 정보 api 연동

frontend/src/apis/channel/index.ts, frontend/src/components/channel/ChannelInfo.tsx, frontend/src/components/channel/HistoryMessages.tsx, frontend/src/components/common/MessageBox.tsx, frontend/src/components/frame/workspace/MainNavigationSidebar.tsx, frontend/src/components/frame/workspace/WorkspaceFrame.tsx, frontend/src/components/workspace/WorkspaceListItem.tsx, frontend/src/hooks/channel/useChatMessages.ts
=> [FE] fix : 오류발생 부분 및 연동 안된 부분을 수정한다

frontend/src/hooks/channel/useChatMessages.ts, frontend/src/pages/workspace/WorkspaceJoinPage.tsx
=> [FE] refactor : 무한스크롤 코드 롤백 및 초대링크를 통한 접속시 전체 채널을 보여주는 기능을 추가한다

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/apis/channel/index.ts, frontend/src/components/common/MessageBox.tsx, frontend/src/components/workspace/WorkspaceChannelPanel/index.tsx, frontend/src/pages/login/ConfirmEmailPage.tsx, frontend/src/stores/userOriginStore.ts, frontend/src/stores/userStore.ts
=> [FE] refactor : zustand persist

frontend/src/pages/login/LoginPage.tsx
=> [FE] feat :  이메일 전송이 사용자 경험을 위한 로딩 컴포넌트를 추가한다
